---
- name: Install haproxy package
  yum:
    name: haproxy
    state: present
  notify: restart haproxy

- name: Gather facts from the web servers
  setup:
    gather_timeout: "10"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['web-servers'] }}"

- name: Set the configuration haproxy.cfg file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Start the haproxy server
  service:
    name: haproxy
    enabled: yes
    state: started

- name: Add haproxy service to firewalld
  firewalld:
    permanent: yes
    port: "{{ haproxy_firewall_port }}/{{ haproxy_firewall_protocol }}"
    state: enabled
    immediate: yes
