- name: Log in (obtain access token)
  community.okd.openshift_auth:
    username: "{{ ocp_user }}"
    password: "{{ ocp_password }}"
    host: "{{ ocp_url }}"
    validate_certs: false
  register: k8s_auth_results

- name: "Expose web port for VMs"
  kubernetes.core.k8s_service:
    validate_certs: false
    host: "{{ ocp_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    state: present
    name: "{{ item }}-web"
    namespace: "{{ namespace }}"
    ports:
    - port: "{{ httpd_firewall_port }}"
      protocol: TCP
    selector:
      vm.kubevirt.io/name: "{{ item }}"
  loop: "{{ groups['webservers'] }}"

- name: "Expose web port for VMs"
  kubernetes.core.k8s_service:
    validate_certs: false
    host: "{{ ocp_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    state: present
    name: "{{ item }}-web"
    namespace: "{{ namespace }}"
    ports:
    - port: "{{ haproxy_firewall_port }}"
      protocol: TCP
    selector:
      vm.kubevirt.io/name: "{{ item }}"
  loop: "{{ groups['haproxy'] }}"

- name: Expose HAProxy Externally
  community.okd.openshift_route:
    validate_certs: false
    host: "{{ ocp_url }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    service: "{{ item }}-web"
    namespace: "{{ namespace }}"
    annotations:
      haproxy.router.openshift.io/balance: roundrobin
    termination: "edge"
  loop: "{{ groups['haproxy'] }}"

