- name: Configure VG
  community.general.lvg:
    vg: data-vg
    pvs: /dev/sda

- name: Configure LV
  community.general.lvol:
    vg: data-vg
    lv: data
    size: 512m
    resizefs: true

- name: Create XFS filesystem
  community.general.filesystem:
    fstype: xfs
    dev: /dev/mapper/data--vg-data

- name: Unmount the LV
  ansible.posix.mount:
    path: /dev/mapper/data--vg-data
    state: unmounted

- name: Create a directory for data-01
  ansible.builtin.file:
    path: "{{ mount_point }}"
    state: directory
    mode: '0755'

- name: Mount to Directory
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: /dev/mapper/data--vg-data
    state: mounted
    fstype: xfs