---
- name: Gather facts from the web servers
  setup:
    gather_timeout: "10"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['webservers'] }}"

- name: Treat faulty web servers
  include_tasks: remove-server-from-haproxy.yml
  loop: "{{ groups['webservers'] }}"