---
- name: Validate the connection to the web server
  uri:
    url: "http://{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  ignore_errors: yes
  register: get_result

- name: test
  debug:
    msg: "{{ get_result['failed'] }}"
  when: get_result.failed == true