---
- name: Validate the connection to the web server
  uri:
    url: "http://{{ hostvars[item]['ansible_facts']['nodename'] }}-web.{{ namespace }}.svc.cluster.local"
  ignore_errors: yes
  register: get_result

- name: Remove faulty server from the HaProxy configuration
  block:
  - name: Remove the faulty server from the HaProxy configutation file
    lineinfile:
      path: /etc/haproxy/haproxy.cfg
      state: absent
      regexp: "{{ hostvars[item]['ansible_facts']['nodename'] }}"

  - name: Restart the HaProxy service
    service:
      name: haproxy
      state: restarted
  when: get_result.failed == true