---
- name: Validate the connection to the web server
  uri:
    url: "http://{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  ignore_errors: yes
  register: get_result

- name: Remove faulty server from the HaProxy configuration
  block:
  - name: Remove the faulty server from the configutation file
    lineinfile:
      path: /etc/haproxy/haproxy.cfg
      state: absent
      regexp: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"

  - name: Restart the HAProxy service
    service:
      name: haproxy
      state: restarted
  when: get_result.failed == true