- name: Automatic Remediation of a webserver
  hosts: all
  sources:
    - name: listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: restart web server
      condition: event.payload.status == "firing"
      action:
        run_job_template:
          name: "Create VirtaulMachines"
          organization: "Platforms Team"
          set_facts: true
