- name: Automatic Remediation of a webserver
  hosts: all
  sources:
    - name: listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: enable selinux
      condition: event.payload.status == "firing"
      actions:
        - debug:
            msg: "{{ event.payload }}"
        - run_job_template:
            name: "Enable SELinux"
            organization: "Platforms Team"
            set_facts: true
            job_args:
              extra_vars:
                alert_status: "{{ event.payload.status }}"
              
