---
- name: Log in (obtain access token)
  community.okd.openshift_auth:
    username: "{{ ocp_user }}"
    password: "{{ ocp_password }}"
    host: "{{ ocp_url }}"
    validate_certs: false
  register: k8s_auth_results

- name: Create "{{ namespace }}" Namespace in OpenShift
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"

- name: "Deploy all VMs"
  include_tasks:
    file: configure-vm.yml
  loop_control:
    loop_var: kubevirt_vm_definition
  loop: "{{ kubevirt_vm }}"