---
- name: Log in (obtain access token)
  community.okd.openshift_auth:
    username: "{{ ocp_user }}"
    password: "{{ ocp_password }}"
    host: "{{ ocp_url }}"
    validate_certs: false
  register: k8s_auth_results

- name: "Deploy all vms"
  include_tasks:
    file: configure-vm.yml
  loop_control:
    loop_var: kubevirt_vm_definition
  loop: "{{ kubevirt_vm }}"