---
- name: Log in (obtain access token)
  k8s_auth:
    username: admin
    password: "{{ ocp_password }}"
    host: "https://api.cluster-4whxk.dynamic.redhatworkshops.io:6443"
  register: k8s_auth_results

- name: "Create VM"
  kubevirt.core.kubevirt_vm:
    state: present
    name: testvm
    namespace: kubevirt-ansible
    validate_certs: false
#    username: "{{ ocp_user }}"
#    password: "{{ ocp_password }}"
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    labels:
      app: test
    instancetype:
      name: u1.medium
    preference:
      name: fedora
    spec:
      domain:
        devices:
          interfaces:
          - name: default
            masquerade: {}
      networks:
      - name: default
        pod: {}
      volumes:
      - containerDisk:
          image: quay.io/containerdisks/fedora:latest
        name: containerdisk
      - cloudInitConfigDrive:
          userData: |-
            #cloud-config
              user: fedora
              password: redhat
              chpasswd: { expire: False }
        name: cloudinit
    wait: yes
